// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_path_ from "./routes/api/[...path].ts";
import * as $api_rec from "./routes/api/rec.ts";
import * as $conditions from "./routes/conditions.tsx";
import * as $home from "./routes/home.tsx";
import * as $index from "./routes/index.tsx";
import * as $play_id_ from "./routes/play/[id].tsx";
import * as $play_random from "./routes/play/random.tsx";
import * as $recording from "./routes/recording.tsx";
import * as $search from "./routes/search.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Player from "./islands/Player.tsx";
import * as $Recoder from "./islands/Recoder.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/[...path].ts": $api_path_,
    "./routes/api/rec.ts": $api_rec,
    "./routes/conditions.tsx": $conditions,
    "./routes/home.tsx": $home,
    "./routes/index.tsx": $index,
    "./routes/play/[id].tsx": $play_id_,
    "./routes/play/random.tsx": $play_random,
    "./routes/recording.tsx": $recording,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Player.tsx": $Player,
    "./islands/Recoder.tsx": $Recoder,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
